//! Finding directories whose contents a build can recreate.
//!
//! This is the question an agent actually has when a disk fills up: not "what
//! is big" but "what is big *and safe to delete*". A 220 GiB `target/` and a
//! 220 GiB photo archive look identical to a scanner, and only one of them can
//! be regenerated by typing `cargo build`.
//!
//! Everything here is read-only. Nothing in this crate deletes anything -- the
//! server reports candidates and a human decides, because a wrong deletion is
//! not recoverable and a wrong report is.

use std::{
    path::{Path, PathBuf},
    time::SystemTime,
};

use hyperdu_core::{scan_directory, Options};

/// A directory of regenerable output.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Candidate {
    pub path: PathBuf,
    /// Which toolchain produced it, so a caller can name the command that
    /// rebuilds it.
    pub kind: Kind,
    pub size_bytes: u64,
    pub files: u64,
    /// Whole days since the newest file we sampled under it. `None` when the
    /// timestamps could not be read.
    pub idle_days: Option<u64>,
}

/// The toolchains whose build output this recognises.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    RustTarget,
    NodeModules,
    PythonVenv,
    PythonCache,
    GradleCache,
}

impl Kind {
    /// The command that puts the directory back, for a caller explaining the
    /// cost of deleting it.
    #[must_use]
    pub fn rebuild_hint(self) -> &'static str {
        match self {
            Self::RustTarget => "cargo build",
            Self::NodeModules => "npm install (or the project's package manager)",
            Self::PythonVenv => "recreate the virtualenv and reinstall requirements",
            Self::PythonCache => "regenerated automatically on next run",
            Self::GradleCache => "gradle build",
        }
    }

    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::RustTarget => "rust-target",
            Self::NodeModules => "node-modules",
            Self::PythonVenv => "python-venv",
            Self::PythonCache => "python-cache",
            Self::GradleCache => "gradle-cache",
        }
    }
}

/// How a directory name maps to a toolchain, and what has to sit beside it for
/// the match to be believable.
///
/// The sibling check exists because `target` is an ordinary English word. A
/// `target/` directory in a data repository is someone's data, and reporting it
/// as reclaimable is exactly the failure that would make this tool unusable.
struct Rule {
    dir_name: &'static str,
    kind: Kind,
    /// A file that must exist in the *parent* directory. `None` when the name
    /// alone is unambiguous.
    requires_sibling: Option<&'static str>,
}

const RULES: &[Rule] = &[
    Rule {
        dir_name: "target",
        kind: Kind::RustTarget,
        requires_sibling: Some("Cargo.toml"),
    },
    // Projects that redirect CARGO_TARGET_DIR out of the way still produce the
    // same contents; the name is distinctive enough to trust on its own.
    Rule {
        dir_name: ".cargo-target",
        kind: Kind::RustTarget,
        requires_sibling: None,
    },
    Rule {
        dir_name: "node_modules",
        kind: Kind::NodeModules,
        requires_sibling: Some("package.json"),
    },
    Rule {
        dir_name: ".venv",
        kind: Kind::PythonVenv,
        requires_sibling: None,
    },
    Rule {
        dir_name: "__pycache__",
        kind: Kind::PythonCache,
        requires_sibling: None,
    },
    Rule {
        dir_name: ".mypy_cache",
        kind: Kind::PythonCache,
        requires_sibling: None,
    },
    Rule {
        dir_name: ".pytest_cache",
        kind: Kind::PythonCache,
        requires_sibling: None,
    },
    Rule {
        dir_name: ".gradle",
        kind: Kind::GradleCache,
        requires_sibling: None,
    },
];

/// Depth of the mtime sample taken inside each candidate.
///
/// Walking every file to find the true newest timestamp costs about a minute
/// on a 20 GiB target directory -- measured, not guessed -- which is more than
/// a tool call should spend. Two levels catch what actually gets touched: cargo
/// rewrites `target/debug/` and `target/.rustc_info.json` on every build, npm
/// rewrites `node_modules/.package-lock.json`. A directory whose top two levels
/// are cold has not been built in recently.
const MTIME_SAMPLE_DEPTH: u32 = 2;

/// Directories never descended into, regardless of depth.
///
/// Recursing into `.git` costs real time and cannot contain build output.
const NEVER_DESCEND: &[&str] = &[".git", ".hg", ".svn"];

const SECONDS_PER_DAY: u64 = 60 * 60 * 24;

/// Find regenerable directories under `root`.
///
/// `min_size_bytes` drops small fry, and `unused_for_days` keeps only
/// candidates whose sampled timestamps are at least that old -- the filter that
/// makes this safe to act on, since a directory an active build is writing to
/// is never idle.
///
/// `max_depth` bounds the search, not the size measurement: a candidate found
/// at the limit is still measured in full. Zero means unlimited, matching
/// [`Options::max_depth`].
pub fn find(
    root: &Path,
    min_size_bytes: u64,
    unused_for_days: Option<u64>,
    max_depth: u32,
) -> Vec<Candidate> {
    let mut found = Vec::new();
    collect(root, 0, max_depth, &mut found);

    let now = SystemTime::now();
    let mut out: Vec<Candidate> = found
        .into_iter()
        .filter_map(|(path, kind)| measure(&path, kind, now))
        .filter(|c| c.size_bytes >= min_size_bytes)
        .filter(|c| match unused_for_days {
            // Unknown age fails the filter: a caller asking for "idle for 7
            // days" wants a guarantee, and we cannot give one here.
            Some(threshold) => c.idle_days.is_some_and(|days| days >= threshold),
            None => true,
        })
        .collect();

    out.sort_by_key(|c| std::cmp::Reverse(c.size_bytes));
    out
}

/// Walk for artifact directories, stopping at each match rather than looking
/// inside it. A `node_modules` nested in a `target` is already accounted for by
/// the enclosing directory's size, and reporting both would double-count.
fn collect(dir: &Path, depth: u32, max_depth: u32, out: &mut Vec<(PathBuf, Kind)>) {
    if max_depth != 0 && depth > max_depth {
        return;
    }
    let Ok(entries) = std::fs::read_dir(dir) else {
        // Permission denied on one subtree should not abort the rest.
        return;
    };

    for entry in entries.flatten() {
        // `file_type` here does not follow symlinks, which keeps a link loop
        // from turning the walk into an infinite one.
        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        if !file_type.is_dir() {
            continue;
        }

        let path = entry.path();
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if NEVER_DESCEND.contains(&name) {
            continue;
        }

        match classify(&path, name) {
            Some(kind) => out.push((path, kind)),
            None => collect(&path, depth + 1, max_depth, out),
        }
    }
}

/// Decide whether `path` is build output, given its own name and what sits
/// beside it.
fn classify(path: &Path, name: &str) -> Option<Kind> {
    let rule = RULES.iter().find(|r| r.dir_name == name)?;
    match rule.requires_sibling {
        Some(sibling) => {
            let parent = path.parent()?;
            parent.join(sibling).is_file().then_some(rule.kind)
        }
        None => Some(rule.kind),
    }
}

fn measure(path: &Path, kind: Kind, now: SystemTime) -> Option<Candidate> {
    let opt = Options::default();
    let stats = scan_directory(path, &opt).ok()?;
    // The scan returns per-directory rows; the root row carries the rolled-up
    // total for the whole subtree.
    let root = stats.get(path)?;

    Some(Candidate {
        path: path.to_path_buf(),
        kind,
        size_bytes: root.physical,
        files: root.files,
        idle_days: newest_mtime(path, MTIME_SAMPLE_DEPTH)
            .and_then(|newest| now.duration_since(newest).ok())
            .map(|age| age.as_secs() / SECONDS_PER_DAY),
    })
}

/// Newest modification time within `depth` levels of `dir`, including `dir`.
///
/// A clock skew that puts a file in the future would otherwise report a
/// negative age as a huge positive one, so callers treat `duration_since`
/// failure as "unknown" rather than "ancient".
fn newest_mtime(dir: &Path, depth: u32) -> Option<SystemTime> {
    let own = std::fs::metadata(dir).and_then(|m| m.modified()).ok();
    if depth == 0 {
        return own;
    }

    let Ok(entries) = std::fs::read_dir(dir) else {
        return own;
    };

    entries
        .flatten()
        .filter_map(|entry| {
            let path = entry.path();
            match entry.file_type() {
                Ok(ft) if ft.is_dir() => newest_mtime(&path, depth - 1),
                Ok(_) => entry.metadata().and_then(|m| m.modified()).ok(),
                Err(_) => None,
            }
        })
        .chain(own)
        .max()
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::*;

    /// Build a tree and return its root. Each entry is a relative path; one
    /// ending in `/` becomes a directory, anything else a file.
    fn tree(entries: &[&str]) -> tempfile::TempDir {
        let dir = tempfile::tempdir().expect("temp dir");
        for entry in entries {
            let path = dir.path().join(entry.trim_end_matches('/'));
            if entry.ends_with('/') {
                fs::create_dir_all(&path).expect("create dir");
            } else {
                if let Some(parent) = path.parent() {
                    fs::create_dir_all(parent).expect("create parent");
                }
                fs::write(&path, b"x").expect("write file");
            }
        }
        dir
    }

    fn names(candidates: &[Candidate]) -> Vec<String> {
        candidates
            .iter()
            .filter_map(|c| c.path.file_name()?.to_str().map(str::to_owned))
            .collect()
    }

    #[test]
    fn finds_a_cargo_target_next_to_a_manifest() {
        let dir = tree(&["Cargo.toml", "target/debug/build.o", "src/main.rs"]);
        let found = find(dir.path(), 0, None, 0);
        assert_eq!(names(&found), vec!["target"]);
        assert_eq!(found[0].kind, Kind::RustTarget);
    }

    #[test]
    fn ignores_a_target_directory_without_a_manifest() {
        // "target" is an ordinary English word. Without a Cargo.toml beside it
        // this is someone's data, and calling it reclaimable would be a
        // recommendation to delete real work.
        let dir = tree(&["target/results.csv", "README.md"]);
        assert!(find(dir.path(), 0, None, 0).is_empty());
    }

    #[test]
    fn ignores_node_modules_without_a_package_manifest() {
        let dir = tree(&["node_modules/vendored.js"]);
        assert!(find(dir.path(), 0, None, 0).is_empty());
    }

    #[test]
    fn finds_node_modules_next_to_a_package_manifest() {
        let dir = tree(&["package.json", "node_modules/left-pad/index.js"]);
        assert_eq!(names(&find(dir.path(), 0, None, 0)), vec!["node_modules"]);
    }

    #[test]
    fn recognises_a_redirected_cargo_target_without_a_sibling_manifest() {
        // CARGO_TARGET_DIR points build output away from the manifest; the
        // distinctive name is the only signal left.
        let dir = tree(&[".cargo-target/debug/app.exe"]);
        let found = find(dir.path(), 0, None, 0);
        assert_eq!(names(&found), vec![".cargo-target"]);
        assert_eq!(found[0].kind, Kind::RustTarget);
    }

    #[test]
    fn does_not_descend_into_a_candidate() {
        // A nested artifact directory is already inside the parent's size;
        // reporting both would double-count the same bytes.
        let dir = tree(&[
            "Cargo.toml",
            "target/debug/node_modules/pkg/index.js",
            "target/debug/package.json",
        ]);
        assert_eq!(names(&find(dir.path(), 0, None, 0)), vec!["target"]);
    }

    #[test]
    fn finds_candidates_in_sibling_projects() {
        let dir = tree(&[
            "a/Cargo.toml",
            "a/target/debug/a.o",
            "b/package.json",
            "b/node_modules/dep/index.js",
        ]);
        let mut found = names(&find(dir.path(), 0, None, 0));
        found.sort();
        assert_eq!(found, vec!["node_modules", "target"]);
    }

    #[test]
    fn min_size_filters_out_small_candidates() {
        let dir = tree(&["Cargo.toml", "target/debug/tiny.o"]);
        // The tree holds a couple of bytes; a gigabyte floor must reject it.
        assert!(find(dir.path(), 1 << 30, None, 0).is_empty());
    }

    #[test]
    fn freshly_written_candidates_fail_an_idle_filter() {
        // This is the safety property that made the filter worth having: a
        // directory an active build is writing to must never be offered up.
        let dir = tree(&["Cargo.toml", "target/debug/just-built.o"]);
        assert!(
            find(dir.path(), 0, Some(1), 0).is_empty(),
            "a directory written to seconds ago is not idle"
        );
        assert_eq!(
            find(dir.path(), 0, None, 0).len(),
            1,
            "and it is still found when no idle filter is asked for"
        );
    }

    #[test]
    fn reports_zero_idle_days_for_a_fresh_candidate() {
        let dir = tree(&["Cargo.toml", "target/debug/fresh.o"]);
        let found = find(dir.path(), 0, None, 0);
        assert_eq!(found[0].idle_days, Some(0));
    }

    #[test]
    fn max_depth_bounds_the_search() {
        let dir = tree(&["deep/nested/Cargo.toml", "deep/nested/target/debug/x.o"]);
        assert!(
            find(dir.path(), 0, None, 1).is_empty(),
            "the candidate sits below the depth limit"
        );
        assert_eq!(
            names(&find(dir.path(), 0, None, 0)),
            vec!["target"],
            "depth 0 means unlimited"
        );
    }

    #[test]
    fn skips_version_control_directories() {
        let dir = tree(&[".git/modules/sub/Cargo.toml", ".git/modules/sub/target/x.o"]);
        assert!(find(dir.path(), 0, None, 0).is_empty());
    }

    #[test]
    fn results_are_sorted_largest_first() {
        let dir = tree(&[
            "small/Cargo.toml",
            "small/target/a.o",
            "big/Cargo.toml",
            "big/target/b1.o",
            "big/target/b2.o",
            "big/target/b3.o",
        ]);
        let found = find(dir.path(), 0, None, 0);
        assert_eq!(found.len(), 2);
        assert!(
            found[0].size_bytes >= found[1].size_bytes,
            "largest candidate must come first"
        );
    }

    #[test]
    fn counts_files_under_a_candidate() {
        let dir = tree(&["Cargo.toml", "target/a.o", "target/b.o", "target/sub/c.o"]);
        let found = find(dir.path(), 0, None, 0);
        assert_eq!(found[0].files, 3);
    }

    #[test]
    fn every_kind_names_a_rebuild_command() {
        for rule in RULES {
            assert!(
                !rule.kind.rebuild_hint().is_empty(),
                "{} must explain how to regenerate it",
                rule.kind.as_str()
            );
        }
    }

    #[test]
    fn returns_nothing_for_a_missing_root() {
        let missing = Path::new("/hyperdu-nonexistent-root-probe-4c81ff");
        assert!(find(missing, 0, None, 0).is_empty());
    }
}
