#!/usr/bin/env bash
set -euo pipefail

# Check that files carrying *this build's* version agree with the workspace.
#
# snap/snapcraft.yaml sat at 0.4.0 while the workspace moved to 0.5.0-beta.2,
# because scripts/package/snap.sh hardcoded the literal while every sibling
# packaging script derived it from `cargo pkgid`. Nothing compared them, so the
# drift shipped. The man page had drifted the same way. This check is what
# would have caught both.
#
# Deliberately NOT checked here: README download links, bucket/hyperdu.json and
# site/_config.yml. Those point at the latest *published release*, which
# legitimately lags the working tree between releases. Forcing them equal would
# fail the moment the workspace version is bumped ahead of a release.

root_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")"/../.. && pwd)"
cd "$root_dir"

# The crate inherits its version from [workspace.package], so the literal is
# not in hyperdu-cli/Cargo.toml. pkgid prints `<url>#<version>`.
ver=$(cargo pkgid -p hyperdu | sed 's/.*[#@]//')
if [[ -z "$ver" ]]; then
  echo "error: could not determine hyperdu version from cargo pkgid" >&2
  exit 1
fi

fail=0
snap_failed=0

check() {
  local file=$1 label=$2 got=$3
  if [[ -z "$got" ]]; then
    echo "error: $file: could not read $label -- the format changed, fix this check" >&2
  elif [[ "$got" != "$ver" ]]; then
    echo "error: $file: $label is '$got', expected '$ver'" >&2
  else
    return 0
  fi
  fail=1
  [[ "$file" == "snap/snapcraft.yaml" ]] && snap_failed=1
  return 0
}

# snapcraft.yaml is generated by scripts/package/snap.sh.
check "snap/snapcraft.yaml" "version" \
  "$(sed -n "s/^version: '\(.*\)'$/\1/p" snap/snapcraft.yaml)"

# The man page ships inside the deb, rpm and Homebrew packages, so a stale
# version here reaches users. Field order is: name, section, source, version.
check "packaging/man/hyperdu.1" ".TH version" \
  "$(sed -n 's/^\.TH [^"]*"[^"]*" "\([^"]*\)".*/\1/p' packaging/man/hyperdu.1)"

# The plugin bundle ships from this repo on the same tag as the crates.
check "plugin/plugin.json" "version" \
  "$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' plugin/plugin.json | head -1)"

if [[ $fail -ne 0 ]]; then
  if [[ $snap_failed -ne 0 ]]; then
    echo "hint: snap/snapcraft.yaml is generated -- run 'bash scripts/package/snap.sh --generate-only'" >&2
  fi
  exit 1
fi

echo "OK: build version strings all match $ver"
