name: ci

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Lint (fmt + clippy)
        run: bash scripts/lint.sh
      - name: Shellcheck scripts
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          shellcheck -S error -x scripts/*.sh
      - name: Import sort (nightly strict)
        run: |
          rustup toolchain install nightly -c rustfmt
          cargo +nightly fmt --all -- --check --config group_imports=StdExternalCrate --config imports_granularity=Crate
      - name: Build
        run: cargo build --workspace --release
      - name: Test core
        run: cargo test -p hyperdu-core -- --nocapture

  # Note: artifact packaging is handled in release.yml on tags. CI only builds and tests.
