name: windows-msi

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-windows-msi:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable

      - name: Install WiX Toolset
        run: choco install wixtoolset -y
        shell: powershell

      - name: Install cargo-wix
        run: cargo install cargo-wix

      - name: Build + Package (ZIP/EXE/MSI)
        shell: powershell
        run: |
          powershell -ExecutionPolicy Bypass -File scripts/package/release.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: windows-msi-and-zips
          path: dist/*
