name: windows-msi

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: {}

jobs:
  build-windows-msi:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install WiX Toolset
        run: choco install wixtoolset -y
        shell: powershell

      - name: Install cargo-wix
        run: cargo install cargo-wix

      - name: Build + Package (ZIP/EXE/MSI)
        shell: powershell
        run: |
          powershell -ExecutionPolicy Bypass -File scripts/package_release.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi-and-zips
          path: dist/*
